#!/usr/bin/env bash

read -p "Enter Pico project name: " project

mkdir -p "$project"
cd "$project"

cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.12)

include(\$ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)

project($project C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

pico_sdk_init()

add_executable(\${PROJECT_NAME}
    main.c
)

pico_add_extra_outputs(\${PROJECT_NAME})

target_link_libraries(\${PROJECT_NAME}
    pico_stdlib
)

pico_enable_stdio_usb(\${PROJECT_NAME} 1)
pico_enable_stdio_uart(\${PROJECT_NAME} 0)
EOF

cat <<EOF > .clangd
CompileFlags:
  CompilationDatabase: build
  Add: [
    "--target=arm-none-eabi",
    "-isystem", "/usr/lib/arm-none-eabi/include",
    "-isystem", "/usr/lib/gcc/arm-none-eabi/13.2.1/include"
  ]
EOF

touch main.c
