#!/usr/bin/env bash

find_dirs=(~/repos ~/stuff ~/)
find_dirs_checked=()
for dir in "${find_dirs[@]}"; do
    if [ -d "$dir" ]; then
        find_dirs_checked+=("$dir")
    fi
done

if [ $# -eq 1 ]; then
    selected=$1
else
    selected=$(find "${find_dirs_checked[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [ -z "$selected" ]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [ -z $TMUX ] && [ -z $tmux_running ]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
