# Neovim modeline making filetype sh so that bashls works
# vim: set filetype=sh:

alias ..='cd ..'
alias pd='pushd'
alias pp='popd'
alias m='less'
alias gvim='gvim.exe'
alias show_folder='explorer.exe .'
alias python='python3'
alias sandbox-c='code ~/Code/C/sandbox'
alias sandbox-ruby='code ~/Code/Ruby/sandbox'
alias luamake=$HOME/lua-language-server/3rd/luamake/luamake
